# Identification du projet
sonar.projectKey=Buy-02
sonar.projectName=Buy-02
sonar.projectVersion=1.0

# On d�finit les dossiers sources (Back et Front)
# Le point (.) designe la racine, mais on precise les inclusions
sonar.sources=backend,frontend/src
sonar.java.binaries=backend/**/target/classes
sonar.java.libraries=**/target/dependency/*.jar

# Exclusions (on ne scanne pas les dependances ni les builds)
sonar.exclusions=frontend/node_modules/**,**/target/**,frontend/dist/**

#Exclusions pour les duplications (CPD)
sonar.cpd.exclusions=**/SecurityConfig.java, **/JwtUtil.java, **/JwtAuthFilter.java, **/ProductRequest.java, **/ProductController.java, **/OrderRequest.java, **/OrderController.java

# Configuration des tests
sonar.tests=backend/media-service/src/test,backend/product-service/src/test,backend/user-service/src/test,backend/order-service/src/test,frontend/src
sonar.test.inclusions=**/*.spec.ts,**/*Test.java

# Rapports de couverture (généré par Maven et Karma)
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info
sonar.coverage.jacoco.xmlReportPaths=backend/media-service/target/site/jacoco/jacoco.xml,backend/product-service/target/site/jacoco/jacoco.xml,backend/user-service/target/site/jacoco/jacoco.xml,backend/order-service/target/site/jacoco/jacoco.xml